apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: helm-push
description: 'Publish a Helm chart'

inputs:
  chart:
    description: Path to the packaged chart.
    required: true
  remote:
    description: Registry to publish the chart to.
    required: true
  commit:
    description: >
      The commit ID from the source repository, used when registering the build artifact in CloudBees platform.
    default: ${{ cloudbees.scm.sha }}
  repository-url:
    description: >
      The clone URL of the source repository, used when registering the build artifact in CloudBees platform.
    default: ${{ cloudbees.scm.repositoryUrl }}
  ref:
    description: >
      The ref or branch of the source repository, used when registering the build artifact in CloudBees platform.
    default: ${{ cloudbees.scm.ref }}
  artifact-name:
    description: >
      The name of the artifact, used when registering the build artifact in CloudBees Unify.
      If not provided, the artifact name defaults to the name of the chart.
    required: false
  component-id:
    description: >
      The ID of the component associated with the artifact. If not provided, the artifact is registered with the component of the current workflow run.
    required: false
    default: ${{ cloudbees.component.id }}


outputs:
  chart:
    description: The image reference pointing to the chart upload location.
    value: ${{ steps.push.outputs.chart }}
  version:
    description: Version of the uploaded chart.
    value: ${{ steps.push.outputs.version }}
  artifact-id:
    description: The unique identifier of the artifact.
    value: ${{ steps.registerArtifact.outputs.artifact-id }}

runs:
  using: composite
  steps:
    - id: push
      name: Publish Helm chart
      uses: docker://alpine/helm:3.18.6
      run: |
        set -u
        CHART_NAME="${ARTIFACT_NAME}"
        if [ -z "$CHART_NAME" ]; then
          CHART_NAME="$(helm show chart "$CHART" | grep -E '^name: ' | sed -E 's/^name: //')"
        fi
        CHART_VERSION="$(helm show chart "$CHART" | grep -E '^version: ' | sed -E 's/^version: //')"
        printf %s "${REMOTE}/${CHART_NAME}" > $CLOUDBEES_OUTPUTS/chart
        printf %s "${CHART_VERSION}" > $CLOUDBEES_OUTPUTS/version
        printf %s "${CHART_NAME}" > $CLOUDBEES_OUTPUTS/chart-name
        set -x
        helm_push_output=$(helm push "$CHART" "$REMOTE" 2>&1)
        if [ $? -eq 0 ]; then
            echo "Chart pushed successfully!"
            echo $helm_push_output
             printf %s "${helm_push_output}" > $CLOUDBEES_OUTPUTS/helm_push_output
            # Extract the digest
            digest=$(echo "$helm_push_output" | grep -i 'Digest' | awk '{print $2}')
            echo "Digest: $digest"
            printf %s "${digest}" > $CLOUDBEES_OUTPUTS/digest
        else
            echo "Failed to push the chart."
            echo "Error: $helm_push_output"
            exit 1
        fi
      env:
        CHART: ${{ inputs.chart }}
        REMOTE: ${{ inputs.remote }}
        ARTIFACT_NAME: ${{ inputs.artifact-name }}
    - id: register-artifact
      name: Register Build Artifact
      if: ${{ steps.push.outputs.helm_push_output && steps.push.outputs.helm_push_output != '' }}
      uses: cloudbees-io/register-build-artifact@v2
      with:
        name: ${{ steps.push.outputs.chart-name }}
        url: ${{ steps.push.outputs.chart }}:${{ steps.push.outputs.version }}
        version: ${{ steps.push.outputs.version }}
        commit: ${{ inputs.commit }}
        ref: ${{ inputs.ref }}
        repository-url: ${{ inputs.repository-url }}
        digest: ${{ steps.push.outputs.digest }}
        component-id: ${{ inputs.component-id }}