apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: helm-push
description: 'Publish a Helm chart'

inputs:
  chart:
    description: Path to the packaged chart.
    required: true
  remote:
    description: Registry to publish the chart to.
    required: true
  send-artifact-info:
    default: 'false'
    description: >
      If set, fails build if registry-mirrors cannot pull image. If registry-mirrors is empty, this flag is ignored.
      Type: Boolean

outputs:
  chart:
    description: The image reference pointing to the chart upload location.
    value: ${{ steps.push.outputs.chart }}
  version:
    description: Version of the uploaded chart.
    value: ${{ steps.push.outputs.version }}

runs:
  using: composite
  steps:
    - id: push
      name: Publish Helm chart
      uses: docker://alpine/helm:3.15.2
      run: |
        set -u
        CHART_NAME="$(helm show chart "$CHART" | grep -E '^name: ' | sed -E 's/^name: //')"
        CHART_VERSION="$(helm show chart "$CHART" | grep -E '^version: ' | sed -E 's/^version: //')"
        printf %s "${REMOTE}/${CHART_NAME}" > $CLOUDBEES_OUTPUTS/chart
        printf %s "${CHART_VERSION}" > $CLOUDBEES_OUTPUTS/version
        set -x
        helm push "$CHART" "$REMOTE"
        
        # Make Platform API call
        requestJson={"runId":"$RUN_ID","run_attempt":$RUN_ATTEMPT,"name":"$CHART_NAME","version":"$CHART_VERSION","url":"$REMOTE","type":"docker"}
        echo $requestJson
        response=$(curl -s --fail-with-body  -X POST \"$URL/v2/workflows/runs/artifactinfos\" -H \"Authorization: Bearer $API_TOKEN\" -H 'Content-Type: application/json' -d $requestJson) || command_failed=1
        # Check curl exit code
        if [ ${command_failed:-0} -eq 1 ];
        then
          echo \"Platform API call failed with error: '$response'\"
        fi  
        echo $response    
      env:
        CHART: ${{ inputs.chart }}
        REMOTE: ${{ inputs.remote }}
        API_TOKEN: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
        RUN_ID: ${{ cloudbees.run_id }}
        RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
