apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: helm-push
description: 'Publish a Helm chart'

inputs:
  chart:
    description: Path to the packaged chart.
    required: true
  remote:
    description: Registry to publish the chart to.
    required: true

outputs:
  chart:
    description: The image reference pointing to the chart upload location.
    value: ${{ steps.push.outputs.chart }}
  version:
    description: Version of the uploaded chart.
    value: ${{ steps.push.outputs.version }}

runs:
  using: composite
  steps:
    - id: push
      name: Publish Helm chart
      uses: docker://alpine/helm:3.15.2
      run: |
        set -u
        CHART_NAME="$(helm show chart "$CHART" | grep -E '^name: ' | sed -E 's/^name: //')"
        CHART_VERSION="$(helm show chart "$CHART" | grep -E '^version: ' | sed -E 's/^version: //')"
        printf %s "${REMOTE}/${CHART_NAME}" > $CLOUDBEES_OUTPUTS/chart
        printf %s "${CHART_VERSION}" > $CLOUDBEES_OUTPUTS/version
        set -x
        helm push "$CHART" "$REMOTE"
        
        curl '$URL/8509888e-d27f-44fa-46a9-29bc76f5e790/artifactinfos' --header 'Authorization: Bearer $API_TOKEN'
        
        # Make Platform API call
        response=$(curl -s --max-time 150 --fail-with-body  -X POST '$URL/v2/workflows/runs/artifactinfos' -H 'Authorization: Bearer $API_TOKEN' -H 'Content-Type: application/json' -d '{\"runId\":\"$RUN_ID\",\"run_attemp\":$RUN_ATTEMPT,\"name\":\"$CHART_NAME\",\"version\":\"$CHART_VERSION\",\"url\":\"$REMOTE\",\"type\":\"docker\"}') || command_failed=1
        # Check curl exit code
        if [ ${command_failed:-0} -eq 1 ];
        then
          echo \"Platform API call failed with error '$response'\"
        fi
      env:
        CHART: ${{ inputs.chart }}
        REMOTE: ${{ inputs.remote }}
        API_TOKEN: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
        RUN_ID: ${{ cloudbees.run_id }}
        RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
